const propertydata = [
  {
      "id": 1,
      "location": "London",
      "date": "2 weeks",
      "price": "$200,000",
      "propertyType": "House",
      "bedrooms": 4,
      "bathrooms": 3,
      "area": 200,
      "imageUrl": "./realestate.jpeg"
  },
  {
      "id": 2,
      "location": "India",
      "date": "3 months",
      "price": "$400,000",
      "propertyType": "Apartment",
      "bedrooms": 2,
      "bathrooms": 2,
      "area": 100,
      "imageUrl": "./realestate2.jpeg"
  },
  {
      "id": 3,
      "location": "Australia",
      "date": "6 months",
      "price": "$500,000",
      "propertyType": "Condo",
      "bedrooms": 2,
      "bathrooms": 2,
      "area": 120,
      "imageUrl": "./realestate3.jpeg"
  },
  {
      "id": 4,
      "location": "America",
      "date": "8 months",
      "price": "$600,000",
      "propertyType": "House",
      "bedrooms": 5,
      "bathrooms": 4,
      "area": 300,
      "imageUrl": "./realestate4.jpeg"
  },
  {
      "id": 5,
      "location": "Dubai",
      "date": "1 year",
      "price": "$800,000",
      "propertyType": "Land",
      "area": 600,
      "imageUrl": "./realestate5.jpeg"
  },
  {
      "id": 6,
      "location": "London",
      "date": "2 weeks",
      "price": "$200,000",
      "propertyType": "House",
      "bedrooms": 4,
      "bathrooms": 3,
      "area": 250,
      "imageUrl": "./realestate.jpeg"
  },
  {
      "id": 7,
      "location": "India",
      "date": "3 months",
      "price": "$400,000",
      "propertyType": "House",
      "bedrooms": 5,
      "bathrooms": 4,
      "area": 350,
      "imageUrl": "./realestate2.jpeg"
  },
  {
      "id": 8,
      "location": "Australia",
      "date": "6 months",
      "price": "$500,000",
      "propertyType": "Apartment",
      "bedrooms": 2,
      "bathrooms": 2,
      "area": 110,
      "imageUrl": "./realestate3.jpeg"
  },
  {
      "id": 9,
      "location": "Dubai",
      "date": "8 months",
      "price": "$600,000",
      "propertyType": "House",
      "bedrooms": 3,
      "bathrooms": 2,
      "area": 180,
      "imageUrl": "./realestate4.jpeg"
  },
  {
      "id": 10,
      "location": "London",
      "date": "1 year",
      "price": "$800,000",
      "propertyType": "Condo",
      "bedrooms": 1,
      "bathrooms": 1,
      "area": 80,
      "imageUrl": "./realestate5.jpeg"
  },
  {
      "id": 11,
      "location": "India",
      "date": "2 weeks",
      "price": "$200,000",
      "propertyType": "Apartment",
      "bedrooms": 3,
      "bathrooms": 2,
      "area": 220,
      "imageUrl": "./realestate.jpeg"
  },
  {
      "id": 12,
      "location": "Australia",
      "date": "3 months",
      "price": "$400,000",
      "propertyType": "House",
      "bedrooms": 3,
      "bathrooms": 2,
      "area": 160,
      "imageUrl": "./realestate2.jpeg"
  },
  {
      "id": 13,
      "location": "Dubai",
      "date": "6 months",
      "price": "$500,000",
      "propertyType": "House",
      "bedrooms": 4,
      "bathrooms": 3,
      "area": 200,
      "imageUrl": "./realestate3.jpeg"
  },
  {
      "id": 14,
      "location": "London",
      "date": "8 months",
      "price": "$600,000",
      "propertyType": "Condo",
      "bedrooms": 2,
      "bathrooms": 1,
      "area": 90,
      "imageUrl": "./realestate4.jpeg"
  },
  {
      "id": 15,
      "location": "India",
      "date": "1 year",
      "price": "$800,000",
      "propertyType": "House",
      "bedrooms": 3,
      "bathrooms": 2,
      "area": 180,
      "imageUrl": "./realestate5.jpeg"
  },
  {
      "id": 16,
      "location": "Australia",
      "date": "2 weeks",
      "price": "$200,000",
      "propertyType": "House",
      "bedrooms": 4,
      "bathrooms": 3,
      "area": 260,
      "imageUrl": "./realestate.jpeg"
  },
  {
      "id": 17,
      "location": "Dubai",
      "date": "3 months",
      "price": "$400,000",
      "propertyType": "Apartment",
      "bedrooms": 2,
      "bathrooms": 1,
      "area": 90,
      "imageUrl": "./realestate2.jpeg"
  },
  {
      "id": 18,
      "location": "London",
      "date": "6 months",
      "price": "$500,000",
      "propertyType": "House",
      "bedrooms": 3,
      "bathrooms": 2,
      "area": 180,
      "imageUrl": "./realestate3.jpeg"
  },
  {
      "id": 19,
      "location": "India",
      "date": "8 months",
      "price": "$600,000",
      "propertyType": "Condo",
      "bedrooms": 1,
      "bathrooms": 1,
      "area": 70,
      "imageUrl": "./realestate4.jpeg"
  },
  {
      "id": 20,
      "location": "Australia",
      "date": "1 year",
      "price": "$800,000",
      "propertyType": "Apartment",
      "bedrooms": 2,
      "bathrooms": 2,
      "area": 180,
      "imageUrl": "./realestate5.jpeg"
  },
  {
      "id": 21,
      "location": "Dubai",
      "date": "2 weeks",
      "price": "$200,000",
      "propertyType": "House",
      "bedrooms": 2,
      "bathrooms": 2,
      "area": 120,
      "imageUrl": "./realestate.jpeg"
  },
  {
      "id": 22,
      "location": "London",
      "date": "3 months",
      "price": "$400,000",
      "propertyType": "Land",
      "area": 400,
      "imageUrl": "./realestate2.jpeg"
  },
  {
      "id": 23,
      "location": "India",
      "date": "6 months",
      "price": "$500,000",
      "propertyType": "House",
      "bedrooms": 4,
      "bathrooms": 3,
      "area": 230,
      "imageUrl": "./realestate3.jpeg"
  },
  {
      "id": 24,
      "location": "Australia",
      "date": "8 months",
      "price": "$600,000",
      "propertyType": "House",
      "bedrooms": 5,
      "bathrooms": 4,
      "area": 320,
      "imageUrl": "./realestate4.jpeg"
  },
  {
      "id": 25,
      "location": "Dubai",
      "date": "1 year",
      "price": "$800,000",
      "propertyType": "House",
      "bedrooms": 4,
      "bathrooms": 3,
      "area": 250,
      "imageUrl": "./realestate5.jpeg"
  },
  {
      "id": 26,
      "location": "London",
      "date": "2 weeks",
      "price": "$200,000",
      "propertyType": "Apartment",
      "bedrooms": 2,
      "bathrooms": 2,
      "area": 100,
      "imageUrl": "./realestate.jpeg"
  },
  {
      "id": 27,
      "location": "India",
      "date": "3 months",
      "price": "$400,000",
      "propertyType": "House",
      "bedrooms": 3,
      "bathrooms": 2,
      "area": 180,
      "imageUrl": "./realestate2.jpeg"
  },
  {
      "id": 28,
      "location": "Australia",
      "date": "6 months",
      "price": "$500,000",
      "propertyType": "Condo",
      "bedrooms": 1,
      "bathrooms": 1,
      "area": 80,
      "imageUrl": "./realestate3.jpeg"
  },
  {
      "id": 29,
      "location": "Dubai",
      "date": "8 months",
      "price": "$600,000",
      "propertyType": "Apartment",
      "bedrooms": 3,
      "bathrooms": 2,
      "area": 220,
      "imageUrl": "./realestate4.jpeg"
  },
  {
      "id": 30,
      "location": "London",
      "date": "1 year",
      "price": "$800,000",
      "propertyType": "House",
      "bedrooms": 2,
      "bathrooms": 2,
      "area": 160,
      "imageUrl": "./realestate5.jpeg"
  },
  {
      "id": 31,
      "location": "India",
      "date": "2 weeks",
      "price": "$200,000",
      "propertyType": "Land",
      "area": 350,
      "imageUrl": "./realestate.jpeg"
  },
  {
      "id": 32,
      "location": "Australia",
      "date": "3 months",
      "price": "$400,000",
      "propertyType": "House",
      "bedrooms": 4,
      "bathrooms": 3,
      "area": 220,
      "imageUrl": "./realestate2.jpeg"
  },
  {
      "id": 33,
      "location": "Dubai",
      "date": "6 months",
      "price": "$500,000",
      "propertyType": "House",
      "bedrooms": 4,
      "bathrooms": 3,
      "area": 250,
      "imageUrl": "./realestate3.jpeg"
  },
  {
      "id": 34,
      "location": "London",
      "date": "8 months",
      "price": "$600,000",
      "propertyType": "House",
      "bedrooms": 4,
      "bathrooms": 3,
      "area": 260,
      "imageUrl": "./realestate4.jpeg"
  },
  {
      "id": 35,
      "location": "India",
      "date": "1 year",
      "price": "$800,000",
      "propertyType": "Apartment",
      "bedrooms": 2,
      "bathrooms": 1,
      "area": 90,
      "imageUrl": "./realestate5.jpeg"
  },
  {
      "id": 36,
      "location": "Australia",
      "date": "2 weeks",
      "price": "$200,000",
      "propertyType": "House",
      "bedrooms": 3,
      "bathrooms": 2,
      "area": 180,
      "imageUrl": "./realestate.jpeg"
  },
  {
      "id": 37,
      "location": "Dubai",
      "date": "3 months",
      "price": "$400,000",
      "propertyType": "Condo",
      "bedrooms": 1,
      "bathrooms": 1,
      "area": 70,
      "imageUrl": "./realestate2.jpeg"
  },
  {
      "id": 38,
      "location": "London",
      "date": "6 months",
      "price": "$500,000",
      "propertyType": "Apartment",
      "bedrooms": 2,
      "bathrooms": 2,
      "area": 180,
      "imageUrl": "./realestate3.jpeg"
  },
  {
      "id": 39,
      "location": "India",
      "date": "8 months",
      "price": "$600,000",
      "propertyType": "House",
      "bedrooms": 2,
      "bathrooms": 2,
      "area": 130,
      "imageUrl": "./realestate4.jpeg"
  },
  {
      "id": 40,
      "location": "Australia",
      "date": "1 year",
      "price": "$800,000",
      "propertyType": "Land",
      "area": 300,
      "imageUrl": "./realestate5.jpeg"
  },
  // Continue adding properties up to 50...
];

export default propertydata;
